---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-toml
  - id: check-vcs-permalinks
  # - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
  - id: requirements-txt-fixer
  - id: end-of-file-fixer
  - id: trailing-whitespace
# - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
#   rev: 0.2.1
#   hooks:
#   - id: yamlfmt
#     args:
#     - --mapping
#     - '2'
#     - --sequence
#     - '2'
#     - --offset
#     - '0'
#     - --width
#     - '150'
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-no-eval
  - id: python-no-log-warn
- repo: https://github.com/asottile/pyupgrade
  rev: v2.28.1
  hooks:
  - id: pyupgrade
    args:
    - --py38-plus

  # TODO: uncomment when refactoring is done
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.950
  #   hooks:
  #   - id: mypy
  #     exclude: ^tests/
  #     args: [--strict, --ignore-missing-imports]

  # Keep last to ensure formatting happens after all other fixes
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
  - id: black-jupyter
